name: release
on:
  push:
    branches: [main]
    paths:
    - 'splayout/__init__.py'
    - '.github/workflows/release.yml'

jobs:
  build_sdist_wheel:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Build SDist and wheel
          run: pipx run build

        - uses: actions/upload-artifact@v4
          with:
            path: dist/*

        - name: Check metadata
          run: pipx run twine check dist/*

  publish:
    needs: [ build_sdist_wheel ]
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
