name: release
on:
  push:
    branches: [main]
    paths:
    - 'splayout/__init__.py'
    - '.github/workflows/release.yml'

jobs:
  build_sdist_wheel:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0

        - name: Build SDist and wheel
          run: pipx run build

        - uses: actions/upload-artifact@v3
          with:
            path: dist/*

        - name: Check metadata
          run: pipx run twine check dist/*